export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POST_DETAIL = 'FETCH_POST_DETAIL'
export const FETCH_POST_DETAIL_FAILD = 'FETCH_POST_DETAIL_FAILD'
export const FETCH_POSTS_FAILD = 'FETCH_POSTS_FAILD'
